package es.mgj.juegohibernate.base;

// Generated 22-ene-2014 15:58:55 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Armas generated by hbm2java
 */
@Entity
@Table(name = "armas", catalog = "juego")
public class Armas implements java.io.Serializable {

	private Integer id;
	private Personajes personajes;
	private String nombre;
	private String descripción;
	private Integer dano;

	public Armas() {
	}

	public Armas(String nombre) {
		this.nombre = nombre;
	}

	public Armas(Personajes personajes, String nombre, String descripción,
			Integer dano) {
		this.personajes = personajes;
		this.nombre = nombre;
		this.descripción = descripción;
		this.dano = dano;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_personaje")
	public Personajes getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Personajes personajes) {
		this.personajes = personajes;
	}

	@Column(name = "nombre", nullable = false, length = 500)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripción", length = 500)
	public String getDescripción() {
		return this.descripción;
	}

	public void setDescripción(String descripción) {
		this.descripción = descripción;
	}

	@Column(name = "dano")
	public Integer getDano() {
		return this.dano;
	}

	public void setDano(Integer dano) {
		this.dano = dano;
	}

}
