package es.mgj.juegohibernate.base;

// Generated 22-ene-2014 15:58:55 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Enemigos generated by hbm2java
 */
@Entity
@Table(name = "enemigos", catalog = "juego")
public class Enemigos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Integer energia;
	private Integer dano;
	private Set<Pantallas> pantallases = new HashSet<Pantallas>(0);

	public Enemigos() {
	}

	public Enemigos(String nombre, Integer energia, Integer dano,
			Set<Pantallas> pantallases) {
		this.nombre = nombre;
		this.energia = energia;
		this.dano = dano;
		this.pantallases = pantallases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 500)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "energia")
	public Integer getEnergia() {
		return this.energia;
	}

	public void setEnergia(Integer energia) {
		this.energia = energia;
	}

	@Column(name = "dano")
	public Integer getDano() {
		return this.dano;
	}

	public void setDano(Integer dano) {
		this.dano = dano;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "enemigo_pantalla", catalog = "juego", joinColumns = { @JoinColumn(name = "id_enemigo", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "id_pantalla", nullable = false, updatable = false) })
	public Set<Pantallas> getPantallases() {
		return this.pantallases;
	}

	public void setPantallases(Set<Pantallas> pantallases) {
		this.pantallases = pantallases;
	}

}
