package es.mgj.juegohibernate.base;

// Generated 22-ene-2014 15:58:55 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Personajes generated by hbm2java
 */
@Entity
@Table(name = "personajes", catalog = "juego")
public class Personajes implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Integer nivel;
	private Integer energia;
	private Integer puntos;
	private Set<Armas> armases = new HashSet<Armas>(0);
	private Set<PersonajePantalla> personajePantallas = new HashSet<PersonajePantalla>(
			0);

	public Personajes() {
	}

	public Personajes(String nombre) {
		this.nombre = nombre;
	}

	public Personajes(String nombre, Integer nivel, Integer energia,
			Integer puntos, Set<Armas> armases,
			Set<PersonajePantalla> personajePantallas) {
		this.nombre = nombre;
		this.nivel = nivel;
		this.energia = energia;
		this.puntos = puntos;
		this.armases = armases;
		this.personajePantallas = personajePantallas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 500)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "nivel")
	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	@Column(name = "energia")
	public Integer getEnergia() {
		return this.energia;
	}

	public void setEnergia(Integer energia) {
		this.energia = energia;
	}

	@Column(name = "puntos")
	public Integer getPuntos() {
		return this.puntos;
	}

	public void setPuntos(Integer puntos) {
		this.puntos = puntos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<Armas> getArmases() {
		return this.armases;
	}

	public void setArmases(Set<Armas> armases) {
		this.armases = armases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personajes")
	public Set<PersonajePantalla> getPersonajePantallas() {
		return this.personajePantallas;
	}

	public void setPersonajePantallas(Set<PersonajePantalla> personajePantallas) {
		this.personajePantallas = personajePantallas;
	}

}
