package es.mgj.juegohibernate.base;

// Generated 22-ene-2014 15:58:55 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Trofeos generated by hbm2java
 */
@Entity
@Table(name = "trofeos", catalog = "juego")
public class Trofeos implements java.io.Serializable {

	private Integer id;
	private Pantallas pantallas;
	private String nombre;
	private Integer puntos;

	public Trofeos() {
	}

	public Trofeos(String nombre) {
		this.nombre = nombre;
	}

	public Trofeos(Pantallas pantallas, String nombre, Integer puntos) {
		this.pantallas = pantallas;
		this.nombre = nombre;
		this.puntos = puntos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pantalla")
	public Pantallas getPantallas() {
		return this.pantallas;
	}

	public void setPantallas(Pantallas pantallas) {
		this.pantallas = pantallas;
	}

	@Column(name = "nombre", nullable = false, length = 500)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "puntos")
	public Integer getPuntos() {
		return this.puntos;
	}

	public void setPuntos(Integer puntos) {
		this.puntos = puntos;
	}

}
